services:
  - type: web
    name: api-produto
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:postgresql://<host>:5432/<database>
      - key: DB_USER
        value: <usuario>
      - key: DB_PASS
        value: <senha>
